version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  katzenhunde:
    lang: node10-express
    handler: ./katzenhunde
    image: alexellis2/katzenhunde:latest
    labels:
      com.openfaas.scale.zero: false
    environment:
#      color: white
      color: citrus
